# Generated by Django 4.1.4 on 2022-12-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_randomuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='default_image/unknow.jpg', upload_to='profile_image/', verbose_name='Изображение профиля'),
        ),
    ]
